# Generated by Django 4.2.28 on 2026-02-07 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentdata',
            name='parameter_name',
        ),
        migrations.RemoveField(
            model_name='equipmentdata',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='equipmentdata',
            name='value',
        ),
        migrations.AddField(
            model_name='equipmentdata',
            name='equipment_type',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='equipmentdata',
            name='flowrate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='equipmentdata',
            name='pressure',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='equipmentdata',
            name='temperature',
            field=models.FloatField(default=0.0),
        ),
    ]
