# Generated by Django 4.2.28 on 2026-02-07 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_remove_equipmentdata_parameter_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentdata',
            name='upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='equipment.uploadhistory'),
        ),
    ]
