# Generated by Django 4.2.28 on 2026-02-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_equipmentdata_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentdata',
            name='numeric_attributes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='uploadhistory',
            name='numeric_columns',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
